SIGNIFICADOS = {
    "AB": "SOlo estudias",
    "AC": "Trabajás por la mañana ",
    "AD": "Trabajás por la tarde",
    "AE": "Trabajás por la noche",
    "AF": "Vas a cursar solo algunas materias",
    "AG": "Vas a cursar todas las materias",
    "AH": "Estás retomando los estudios después de un tiempo",
    "AI": "Estás estudiando dos carreras a la vez",
    "A": "Dedicar una hora por turno",
    "B": "Seguir el ritmo de la materia",
    "C": "Rendir finales apenas termina",
    "D": "Promocionar materias",
    "E": "Asistir a todas las clases",
    "F": "Dedicación fija por materia",
    "G": "Organizar tiempos por doble turno",
    "H": "Priorizar materias para no sobrecargarse",
    "I": "Motivar a continuar la carrera",
    "J": "No tiene método de estudio",
    "K": "Recomendar técnica de estudio",
    "L": "Mostrar horario de mañana",
    "M": "Recomendar clases virtuales",
    "N": "Mostrar horario de tarde",
    "O": "Dificultad para retomar el ritmo",
    "P": "Método de estudio",
    "Q": "Dificultad para entender materias",
    "R": "Cursos nivelatorios",
    "S": "Tutores académicos",
    "T": "Materias troncales",
    "U": "Aprovechar tiempo libre",
    "V": "Clases presenciales",
    "W": "Clases de consulta",
    "X": "Usar mapa conceptual",
    "Y": "Consultar a un compañero",
    "Z": "Buscar en internet",
    "AA": "Evitar superposición horaria",
    "BB": "Riesgo de estrés",
    "CC": "Actividades recreativas",
    "DD": "Consultar planes para equivalencias",
    "EE": "Priorizar materias comunes entre carreras",
    "FF": "Disponibilidad de tiempo",
    "GG": "Sobrecarga académica",
    "HH": "Necesidad de horarios flexibles",
    "II": "Motivar manejo del estrés",
    "JJ": "Cursar cuando esté más descansado",
    "KK": "Buena organización de cursado",
    "LL": "Plan de horarios",
    "MM": "Plan de estudio diario",
    "NN": "Priorizar carrera principal",
    "OO": "Usar Google Calendar",
    "PP": "Llegar descansado a parciales",
    "QQ": "Dificultad para asistir a clases",
    "RR": "Plan de descanso adecuado",
    "SS": "Apoyo con materiales virtuales",
    "TT": "Armar cronograma de clases",
    #------------------------------------
    "UU": "Tiene dificultad teorica",
    "U1": "Hacer resúmenes entendiendo el tema",
    "U2": "Subrayar conceptos claves",
    "U3": "Hacer diagramas",
    "VV": "Tiene dificultad en la parte práctica",
    "V1": "Intentar resolver ejercicios",
    "W":  "Ir a clases de consulta"
    
    
    
}
